### ISSUE TITLE
Python missing methods

### ISSUE THREAD

**Issue by abroutin** [zeromq/ingescape#46]
Some methods are not implemented in Python:
- igs_service_args_clone
- igs_command_line
- igs_log_no_warning_if_undefined_service

**Comment by abroutin** [comment]
To check: 

- igs_channel_join
- igs_channel_leave
- igs_channel_shout_str
- igs_channel_shout_data
- igs_channel_whisper_str
- igs_channel_whisper_data
- igs_peer_add_header
- igs_peer_remove_header

**Comment by Mathsoum** [comment]
All these methods are now implemented in the python binding.
Closing
